services:
  uni_class_game_frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: uni_class_game_frontend
    ports:
      - "3000:80"
        #- "5173:80"
    depends_on:
      - uni_class_game_backend
    networks:
      - app-network
    environment:
      - VITE_UNI_CLASS_BACKEND_HOST=${VITE_UNI_CLASS_BACKEND_HOST}

  uni_class_game_backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    container_name: uni_class_game_backend
    depends_on:
      - redis_server
    ports:
      - "5173:3000"
    networks:
      - app-network
    environment:
      - REDIS_CONNECTION_URL=${REDIS_CONNECTION_URL}

  redis_server:
    image: redis:7-alpine
    container_name: redis_server
    volumes:
      - ./redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
