export interface Stock {
  id: string;
  name: string;
  quantity: number;
  priceSell?: number; // tiền cần có để mua trong shop
  priceReWard?: number; // tiền nhận được khi bán xong
  enabled: boolean;
  currentIndexLevel: number; // level hiện tại của món ăn -> dùng để map số tiền mua trong shop và tiền nhận đc sau khi bán xong
  sellPrices: number[]; // giá tiền để mua trong shop
  rewardPrices: number[]; // tiền nhận được sau khi bán;
  isDefaultSell?: boolean; // MÓn ăn mặc định có sẵn trong cửa hàng
}

export interface Question {
  id: string;
  text: string;
  answers: { id: string; text: string }[]; // danh sách đáp án
  correctAnswerId: string; // id của đáp án đúng
}

export interface ShopItem {
  id: string;
  stockId: string;
  enabled: boolean; // true nếu có thể mua
}

export interface OrderItem {
  stockId: string;
  quantity: number;
}

export interface Customer {
  id: string;
  name: string;
  avatar: string;
  avatarId: number;
  orders: OrderItem[];
  originalOrders: OrderItem[];
  position: number;
  firstLoad: boolean;
}

export interface Ability {
  id: number;
  name: string;
  description: string;
  price: number;
  enabled: boolean;
  purchased: boolean;
  isActive: boolean;
}

export const STOCKS = [
  {
    id: "s1",
    name: "Toast",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [0, 300, 5250, 42500, 130000, 600000],
    rewardPrices: [2, 53, 525, 1750, 3500, 10000],
    image: "blook-toast",
  },
  {
    id: "s2",
    name: "Cereal",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [5, 1500, 16250, 212500, 650000],
    rewardPrices: [18, 263, 2625, 8750, 17500],
    image: "blook-cereal",
  },
  {
    id: "s3",
    name: "Yogurt",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [10, 4500, 78750, 637500, 1950000],
    rewardPrices: [53, 788, 7875, 26250, 52500],
    image: "blook-yogurt",
  },
  {
    id: "s4",
    name: "Breakfast Combo",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [50, 9000, 157500, 1275000, 3900000],
    rewardPrices: [105, 1575, 15750, 52500, 105000],
    image: "blook-breakfast",
  },
  {
    id: "s5",
    name: "Orange Juice",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [200, 15000, 262500, 2125000, 6500000],
    rewardPrices: [175, 2625, 26250, 87500, 175000],
    image: "blook-orange-carton",
  },
  {
    id: "s6",
    name: "Milk",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [500, 22500, 393750, 3187500, 9750000],
    rewardPrices: [263, 3938, 39375, 131250, 262500],
    image: "blook-milk-carton",
  },
  {
    id: "s7",
    name: "Waffle",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [2000, 31500, 551250, 4462500, 13650000],
    rewardPrices: [368, 5513, 55125, 183750, 367500],
    image: "blook-waffle",
  },
  {
    id: "s8",
    name: "Pancakes",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [5000, 420000, 735000, 5950000, 18200000],
    rewardPrices: [490, 7350, 245000, 490000],
    image: "blook-pancake",
  },
  {
    id: "s9",
    name: "French Toast",
    quantity: 0,
    enabled: false,
    currentIndexLevel: 0,
    sellPrices: [7500, 54000, 2945000, 7650000, 23400000],
    rewardPrices: [630, 9450, 94500, 315000, 630000],
    image: "blook-french-waffle",
  },
];

export const QUESTIONS = [
  {
    id: "q1",
    text: "Chiến lược UNICLASS năm học 2025-2026 là gì?",
    answers: [
      { id: "a1", text: "Học là thích" },
      { id: "a2", text: "Sự tiến bộ" },
      { id: "a3", text: "Học là vui" },
      { id: "a4", text: "Học nữa học mãi" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q2",
    text: "Uniclass hiện đang dạy học sinh từ lớp mấy đến lớp mấy?",
    answers: [
      { id: "a1", text: "Lớp 1 đến lớp 12" },
      { id: "a2", text: "Lớp 1 đến lớp 9" },
      { id: "a3", text: "Lớp 1 đến lớp 5" },
      { id: "a4", text: "Lớp 1 đến lớp 7" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q3",
    text: "Uniclass dạy theo hình thức nào?",
    answers: [
      { id: "a1", text: "BigClass Steam trực tiếp" },
      { id: "a2", text: "App tự học" },
      { id: "a3", text: "Video không có tương tác" },
      { id: "a4", text: "Học qua video youtube" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q4",
    text: "12 × 8 = ?",
    answers: [
      { id: "a1", text: "96" },
      { id: "a2", text: "88" },
      { id: "a3", text: "108" },
      { id: "a4", text: "86" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q5",
    text: "Số nguyên tố nhỏ nhất là?",
    answers: [
      { id: "a1", text: "0" },
      { id: "a2", text: "1" },
      { id: "a3", text: "2" },
      { id: "a4", text: "3" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q6",
    text: "Chu vi hình vuông cạnh 5 cm là?",
    answers: [
      { id: "a1", text: "10" },
      { id: "a2", text: "20" },
      { id: "a3", text: "25" },
      { id: "a4", text: "15" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q7",
    text: "3/4 + 1/4 = ?",
    answers: [
      { id: "a1", text: "3/8" },
      { id: "a2", text: "1" },
      { id: "a3", text: "4/8" },
      { id: "a4", text: "2" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q8",
    text: "Tác giả của “Truyện Kiều” là ai?",
    answers: [
      { id: "a1", text: "Nguyễn Trãi" },
      { id: "a2", text: "Hồ Xuân Hương" },
      { id: "a3", text: "Tố Hữu" },
      { id: "a4", text: "Nguyễn Du" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q9",
    text: "Nhân vật Thánh Gióng ăn gì để lớn nhanh?",
    answers: [
      { id: "a1", text: "Cháo hành" },
      { id: "a2", text: "Cơm và rau muống luộc" },
      { id: "a3", text: "Thịt gà" },
      { id: "a4", text: "Trái cây" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q10",
    text: "Câu tục ngữ: “Có công mài sắt…” tiếp theo là?",
    answers: [
      { id: "a1", text: "Có ngày sáng loáng" },
      { id: "a2", text: "Có ngày nên kim" },
      { id: "a3", text: "Có ngày thành thép" },
      { id: "a4", text: "Có ngày thành kim" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q11",
    text: '"I love Uniclass" nghĩa là?',
    answers: [
      { id: "a1", text: "Tôi yêu em" },
      { id: "a2", text: "Tôi học Uniclass" },
      { id: "a3", text: "Tôi yêu Uniclass" },
      { id: "a4", text: "Tôi đăng ký Uniclass" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q12",
    text: "Trái đất quay quanh Mặt trời mất bao lâu?",
    answers: [
      { id: "a1", text: "30 ngày" },
      { id: "a2", text: "365 ngày" },
      { id: "a3", text: "24h" },
      { id: "a4", text: "1000 ngày" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q13",
    text: 'Loài vật nào được gọi là "vua của muôn loài"?',
    answers: [
      { id: "a1", text: "Cá mập" },
      { id: "a2", text: "Gấu" },
      { id: "a3", text: "Hổ" },
      { id: "a4", text: "Sư tử" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q14",
    text: "Chùa Một Cột nằm ở thành phố nào?",
    answers: [
      { id: "a1", text: "Huế" },
      { id: "a2", text: "Hà Nội" },
      { id: "a3", text: "Đà Nẵng" },
      { id: "a4", text: "TP. Hồ Chí Minh" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q15",
    text: "Ngọn núi nào cao nhất thế giới?",
    answers: [
      { id: "a1", text: "Phan Xi Păng" },
      { id: "a2", text: "Kilimanjaro" },
      { id: "a3", text: "Alps" },
      { id: "a4", text: "Everest" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q16",
    text: "Tác giả của truyện “Dế Mèn phiêu lưu ký” là ai?",
    answers: [
      { id: "a1", text: "Ngô Tất Tố" },
      { id: "a2", text: "Nguyễn Nhật Ánh" },
      { id: "a3", text: "Nam Cao" },
      { id: "a4", text: "Tô Hoài" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q17",
    text: "Một năm nhuận có bao nhiêu ngày?",
    answers: [
      { id: "a1", text: "365" },
      { id: "a2", text: "366" },
      { id: "a3", text: "367" },
      { id: "a4", text: "364" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q18",
    text: "Một giờ có bao nhiêu phút?",
    answers: [
      { id: "a1", text: "30" },
      { id: "a2", text: "60" },
      { id: "a3", text: "90" },
      { id: "a4", text: "120" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q19",
    text: "Một thế kỷ bằng bao nhiêu năm?",
    answers: [
      { id: "a1", text: "10" },
      { id: "a2", text: "50" },
      { id: "a3", text: "100" },
      { id: "a4", text: "1000" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q20",
    text: "7 × 9 = ?",
    answers: [
      { id: "a1", text: "63" },
      { id: "a2", text: "72" },
      { id: "a3", text: "64" },
      { id: "a4", text: "54" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q21",
    text: "(–3) + 5 = ?",
    answers: [
      { id: "a1", text: "-2" },
      { id: "a2", text: "2" },
      { id: "a3", text: "8" },
      { id: "a4", text: "0" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q22",
    text: "Tác phẩm nào mở đầu bằng câu “Ngày xửa ngày xưa…”?",
    answers: [
      { id: "a1", text: "Truyện cổ tích" },
      { id: "a2", text: "Thơ ca" },
      { id: "a3", text: "Truyện ngắn" },
      { id: "a4", text: "Tục ngữ" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q23",
    text: "“Lão Hạc” là tác phẩm của ai?",
    answers: [
      { id: "a1", text: "Ngô Tất Tố" },
      { id: "a2", text: "Kim Lân" },
      { id: "a3", text: "Nam Cao" },
      { id: "a4", text: "Nguyễn Du" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q24",
    text: "Tác phẩm “Đồng chí” nói về ai?",
    answers: [
      { id: "a1", text: "Người đồng hành" },
      { id: "a2", text: "Người nông dân" },
      { id: "a3", text: "Đôi bạn cùng tiến" },
      { id: "a4", text: "Người lính kháng chiến" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q25",
    text: "Số 15 trong tiếng Anh là?",
    answers: [
      { id: "a1", text: "Fifteen" },
      { id: "a2", text: "Fifty" },
      { id: "a3", text: "Fiveteen" },
      { id: "a4", text: "Fifty five" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q26",
    text: "Hành tinh nào gần Mặt trời nhất?",
    answers: [
      { id: "a1", text: "Sao Thuỷ" },
      { id: "a2", text: "Sao Hoả" },
      { id: "a3", text: "Sao Kim" },
      { id: "a4", text: "Trái đất" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q27",
    text: "Thể tích hình lập phương cạnh 3 cm là",
    answers: [
      { id: "a1", text: "18" },
      { id: "a2", text: "27" },
      { id: "a3", text: "9" },
      { id: "a4", text: "81" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q28",
    text: "(–7) – (–5) = ?",
    answers: [
      { id: "a1", text: "-12" },
      { id: "a2", text: "2" },
      { id: "a3", text: "12" },
      { id: "a4", text: "-2" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q29",
    text: "Ngày Nhà giáo Việt Nam là ngày nào?",
    answers: [
      { id: "a1", text: "20/11" },
      { id: "a2", text: "2/9" },
      { id: "a3", text: "20/10" },
      { id: "a4", text: "21/11" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q30",
    text: "Con người có bao nhiêu xương?",
    answers: [
      { id: "a1", text: "210" },
      { id: "a2", text: "206" },
      { id: "a3", text: "150" },
      { id: "a4", text: "300" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q31",
    text: "Tầng nào của khí quyển chứa khí Ozon bảo vệ Trái Đất?",
    answers: [
      { id: "a1", text: "Tầng đối lưu" },
      { id: "a2", text: "Tầng bình lưu" },
      { id: "a3", text: "Tầng trung lưu" },
      { id: "a4", text: "Tầng ngoài" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q32",
    text: "Bài thơ nào mở đầu bằng câu “Sông Mã xa rồi Tây Tiến ơi”?",
    answers: [
      { id: "a1", text: "Việt Bắc" },
      { id: "a2", text: "Đồng chí" },
      { id: "a3", text: "Sóng" },
      { id: "a4", text: "Tây Tiến" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q33",
    text: "Nhà Trần đã 3 lần đánh bại quân xâm lược nào?",
    answers: [
      { id: "a1", text: "Quân Nguyên Mông" },
      { id: "a2", text: "Quân nhà Minh" },
      { id: "a3", text: "Quân nhà Thanh" },
      { id: "a4", text: "Pháp" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q34",
    text: "Năm nào Bác Hồ đọc Tuyên ngôn độc lập?",
    answers: [
      { id: "a1", text: "1954" },
      { id: "a2", text: "1945" },
      { id: "a3", text: "1930" },
      { id: "a4", text: "1975" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q35",
    text: "“By next year, I ____ English for 5 years.”",
    answers: [
      { id: "a1", text: "have learned" },
      { id: "a2", text: "learn" },
      { id: "a3", text: "will have learned" },
      { id: "a4", text: "learned" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q36",
    text: "Ánh sáng đi từ Mặt trời đến Trái Đất mất khoảng?",
    answers: [
      { id: "a1", text: "8 phút 20 giây" },
      { id: "a2", text: "1 giờ" },
      { id: "a3", text: "24h" },
      { id: "a4", text: "3 phút" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q37",
    text: "DNA nằm ở đâu trong tế bào?",
    answers: [
      { id: "a1", text: "Nhân" },
      { id: "a2", text: "Tế bào chất" },
      { id: "a3", text: "Màng tế bào" },
      { id: "a4", text: "Ty thể" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q38",
    text: "Khí nào chiếm nhiều nhất trong không khí Trái Đất?",
    answers: [
      { id: "a1", text: "Oxy" },
      { id: "a2", text: "C02" },
      { id: "a3", text: "Heli" },
      { id: "a4", text: "Ni tơ" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q39",
    text: "“I have ___ apple.”",
    answers: [
      { id: "a1", text: "an" },
      { id: "a2", text: "a" },
      { id: "a3", text: "the" },
      { id: "a4", text: "one" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q40",
    text: "Which is a preposition?",
    answers: [
      { id: "a1", text: "book" },
      { id: "a2", text: "on" },
      { id: "a3", text: "run" },
      { id: "a4", text: "fast" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q41",
    text: "Số tiếp theo của dãy: 2, 4, 8, 16, ?",
    answers: [
      { id: "a1", text: "18" },
      { id: "a2", text: "20" },
      { id: "a3", text: "32" },
      { id: "a4", text: "64" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q42",
    text: "“AI” là viết tắt của gì?",
    answers: [
      { id: "a1", text: "Automatic Input" },
      { id: "a2", text: "Artificial Intelligence" },
      { id: "a3", text: "Advanced Internet" },
      { id: "a4", text: "Applied Information" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q43",
    text: "Doraemon thích ăn món gì?",
    answers: [
      { id: "a1", text: "Bánh rán" },
      { id: "a2", text: "Susjo" },
      { id: "a3", text: "Pizza" },
      { id: "a4", text: "Hamburger" },
    ],
    correctAnswerId: "a1",
  },
  {
    id: "q44",
    text: "Thủ môn nổi tiếng người Việt Nam – AFF Cup 2018?",
    answers: [
      { id: "a1", text: "Tiến Dũng" },
      { id: "a2", text: "Đặng Văn Lâm" },
      { id: "a3", text: "Quang Hải" },
      { id: "a4", text: "Công Phượng" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q45",
    text: "Kim loại nào dẫn điện tốt nhất?",
    answers: [
      { id: "a1", text: "Vàng" },
      { id: "a2", text: "Bạc" },
      { id: "a3", text: "Đồng" },
      { id: "a4", text: "Sắt" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q46",
    text: "Giá trị của π (pi) gần bằng?",
    answers: [
      { id: "a1", text: "2.14" },
      { id: "a2", text: "3.14" },
      { id: "a3", text: "4.14" },
      { id: "a4", text: "5.14" },
    ],
    correctAnswerId: "a2",
  },
  {
    id: "q47",
    text: "“Chị Dậu” là nhân vật trong tác phẩm nào?",
    answers: [
      { id: "a1", text: "Vợ nhặt" },
      { id: "a2", text: "Số đỏ" },
      { id: "a3", text: "Chí phèo" },
      { id: "a4", text: "Tắt đèn" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q48",
    text: "Ánh sáng Mặt Trăng thực chất là gì?",
    answers: [
      { id: "a1", text: "Ánh sáng của Mặt Trăng" },
      { id: "a2", text: "Ánh sáng của sao" },
      { id: "a3", text: "Phản chiếu ánh sáng Mặt Trời" },
      { id: "a4", text: "Ánh sáng phát ra từ đất" },
    ],
    correctAnswerId: "a3",
  },
  {
    id: "q49",
    text: "0, 1, 1, 2, 3, 5, 8, ? (dãy Fibonacci)",
    answers: [
      { id: "a1", text: "10" },
      { id: "a2", text: "11" },
      { id: "a3", text: "12" },
      { id: "a4", text: "13" },
    ],
    correctAnswerId: "a4",
  },
  {
    id: "q50",
    text: "Vị vua nào lập ra triều Lý ở Việt Nam?",
    answers: [
      { id: "a1", text: "Lý Thường Kiệt" },
      { id: "a2", text: "Lý Công Uẩn" },
      { id: "a3", text: "Lý Nhân Tông" },
      { id: "a4", text: "Lý Chiêu Hoàng" },
    ],
    correctAnswerId: "a2",
  },
];

export enum ABILITY_ID {
  PAYCHECK_BONUS = 1,
  SUPPLY_CRATE = 2,
  HAPPY_CUSTOMER = 3,
  TRASH_THE_FOOD = 4,
  TAXES = 5,
  HEALTH_INSPECTION = 6,
  RUN_IT_BACK = 7,
}

export const REQUIRE_PLAYER_ABILITES = [
  ABILITY_ID.PAYCHECK_BONUS,
  ABILITY_ID.TRASH_THE_FOOD,
  ABILITY_ID.TAXES,
  ABILITY_ID.HEALTH_INSPECTION,
];

export const ABILITIES = [
  {
    id: ABILITY_ID.PAYCHECK_BONUS,
    name: "Paycheck Bonus",
    description: "Give a player +25% of their balance",
    price: 500,
    enabled: false,
    purchased: false,
    isActive: false,
    image: "abilities-paycheck",
    descriptionEnemy: "just increase your balance by 25%",
  },
  {
    id: ABILITY_ID.SUPPLY_CRATE,
    name: "Supply Crate",
    description: "+7 stock all of your foods",
    price: 1000,
    enabled: false,
    purchased: false,
    isActive: true,
    image: "abilites-supply",
  },
  {
    id: ABILITY_ID.HAPPY_CUSTOMER,
    name: "Happy Customer",
    description: "Your next 5 customers pay double",
    price: 2500,
    enabled: false,
    purchased: false,
    isActive: true,
    image: "abilities-happy",
  },
  {
    id: ABILITY_ID.TRASH_THE_FOOD,
    name: "Trash the Food",
    description: "Lower a players food stocks by 3 each",
    price: 5000,
    enabled: false,
    purchased: false,
    isActive: false,
    image: "abilites-trash",
    descriptionEnemy: "just decreased your food stocks by 3",
  },
  {
    id: ABILITY_ID.TAXES,
    name: "TAXES!",
    description: "Reduce a players balance by 25%",
    price: 7500,
    enabled: false,
    purchased: false,
    isActive: false,
    image: "abilites-taxes",
    descriptionEnemy: "just decreased your balance by 25%",
  },
  {
    id: ABILITY_ID.HEALTH_INSPECTION,
    name: "Health Inspection",
    description: "Force a player to get a 12s",
    price: 10000,
    enabled: false,
    purchased: false,
    isActive: false,
    image: "abilites-health",
  },
  {
    id: ABILITY_ID.RUN_IT_BACK,
    name: "Run It Back",
    description: "Be able to buy all your abilities again",
    price: 150000,
    enabled: false,
    purchased: false,
    isActive: true,
    image: "abilities-run",
  },
];

export const AVATARS_CUSTOMER = [
  "chick",
  "chicken",
  "cow",
  "goat",
  "horse",
  "pig",
  "sheep",
  "duck",
  "alpaca",
  "dog",
  "cat",
  "rabbit",
  "goldfish",
  "hamster",
  "turtle",
  "kitten",
  "puppy",
  "bear",
  "moose",
  "fox",
  "raccoon",
  "squirrel",
  "owl",
  "hedgehog",
  "deer",
  "wolf",
  "beaver",
  "tiger",
  "orangutan",
  "cockatoo",
  "parrot",
  "anaconda",
  "jaguar",
  "macaw",
  "toucan",
  "panther",
  "capuchinmonkey",
  "gorilla",
  "hippo",
  "rhino",
  "giraffe",
  "snowyowl",
  "polarbear",
  "arcticfox",
  "babypenguin",
  "penguin",
  "arctichare",
  "seal",
  "walrus",
  "witch",
  "wizard",
  "elf",
  "fairy",
  "slimemonster",
  "jester",
  "dragon",
  "queen",
  "unicorn",
  "king",
  "twoofspades",
  "eat",
  "drink",
  "alice",
  "queenofhearts",
  "dormouse",
  "whiterabbit",
  "cheshirecat",
  "caterpillar",
  "madhatter",
  "kingofhearts",
  "toast",
  "cereal",
  "yogurt",
  "breakfastcombo",
  "orangejuice",
  "milk",
  "waffle",
  "pancakes",
  "frenchtoast",
  "pizza",
  "earth",
  "meteor",
  "stars",
  "alien",
  "planet",
  "ufo",
  "spaceship",
  "astronaut",
  "lilbot",
  "lovelybot",
  "angrybot",
  "happybot",
  "watson",
  "buddybot",
  "brainybot",
  "megabot",
  "oldboot",
  "jellyfish",
  "clownfish",
  "frog",
  "crab",
  "pufferfish",
  "blobfish",
  "octopus",
  "narwhal",
  "dolphin",
  "babyshark",
  "megalodon",
  "panda",
  "sloth",
  "tenrec",
  "flamingo",
  "zebra",
  "elephant",
  "lemur",
  "peacock",
  "chameleon",
  "lion",
  "amber",
  "dinoegg",
  "dinofossil",
  "stegosaurus",
  "velociraptor",
  "brontosaurus",
  "triceratops",
  "tyrannosaurusrex",
  "icebat",
  "icebug",
  "iceelemental",
  "rockmonster",
  "dink",
  "donk",
  "bushmonster",
  "yeti",
  "dingo",
  "echidna",
  "koala",
  "kookaburra",
  "platypus",
  "joey",
  "kangaroo",
  "crocodile",
  "sugarglider",
  "deckhand",
  "buccaneer",
  "swashbuckler",
  "treasuremap",
  "seagull",
  "jollypirate",
  "pirateship",
  "kraken",
  "captainblackbeard",
  "ant",
  "rhinobeetle",
  "ladybug",
  "fly",
  "worm",
  "bee",
  "mantis",
  "butterfly",
  "bananas",
  "watermelon",
  "cheese",
  "doughnut",
  "taco",
  "bao",
  "sushi",
  "cheeseburger",
  "sandwich",
  "pumpkin",
  "swampmonster",
  "frankenstein",
  "vampire",
  "zombie",
  "mummy",
  "caramelapple2",
  "candycorn",
  "crow",
  "werewolf",
  "ghost",
  "blackbear",
  "pumpkinpie",
  "chipmunk",
  "cornucopia",
  "autumncat",
  "pumpkinpuppy",
  "autumncrow",
  "turkey",
  "snowglobe",
  "holidaygift",
  "hotchocolate",
  "holidaywreath",
  "stocking",
  "gingerbreadman",
  "gingerbreadhouse",
  "reindeer",
  "snowman",
  "santaclaus",
];
